language: python
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"    # will not support versions lower than Python 3.6
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"  # 3.9 development branch
before_script:
  # - make --version
  # - python --version
  - make configure
scripts:
  - make test
# after_script:
  - printenv
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]];
    then make docs;
    sonar-scanner;
    fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "lunaticthinker-me"
    token:
      secure: "S7YWj9EuSUXz/qlctqN1X5l/rcjVYWVNSrhji0MbHwDFuYzdIB+ZpUMogDelnq7LoXtGwvuvZQJTt0/0lLOYMvJm0DMh6Qt5NrG2w6CgHDzAW8cbm9qiCowzrmVI5FDMc7FB5sKn7pbhVRnCqQC46x7kDQiIWcU1aNlZUiSSaNWYVAP8jItDXPgj9lO35B+7kkMtPhOgv+ycTMZTa917GRCS7XxEhynXGFAPBmwXf5jJJiIqBEv30hLIGKe+Bwadwtp1I6Y0/tqPXD09ZHn2Gsl8AyV8xjM74Zt1NmvM1hFrNWoJhhVJa2F7l2qkMbNilvdsL9ETP4p/T+uuMz6tDvlAU0L81ZwKzNnzVob0f3IxfgPwj0p/MjtgURY0VbwqMSxvif2EkcVrUvv7rN0WmfgWNSaGt8gCpR1bP5WRfyvzdmHjDa+Gq1nmaEPkJmN4eTpthS42kgXQnuLIagzzEpuCzTg6bVr/g8u4YLrjkI6QaCtBQsftpy6UPrCtClGafk9E/MK/381TfMGCPP/hjVzhkL6CDYdjM8EpsPRlUeRslhCD9BOy3951Cmbc5mAy5YIzUYmMDdMMOOCSzprgGQRp5pVcQ+1iGVqzNHYBcdyLVn/hhHxRZ8XSgwaT3h/+OX2FHxpg0Zb0t4hVQMuJKK3V0kcAzwPyFou6JKOptrw="
