language: python
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"    # will not support versions lower than Python 3.6
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"  # 3.9 development branch
before_script:
  # - make --version
  # - python --version
  - make configure
scripts:
  - make test
# after_script:
  - printenv
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]];
    then make docs;
    sonar-scanner;
    fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "lunaticthinker-me"
    token:
      secure: "sUI2pbaTpK9QbDvmVe8HrK+ojerv6kxS5IwXqKd22VoZgszg/rjbjqvBNPqXtA+Mh2hk2Q9VcRObw2hitgh69XAUHrvlvnJ1k0D42zrLaHMkzTNn5hclClEOIwfyLhmKjGwFUA+roeSQkA1rWkANe1g9VoEGYZbZ3vHI45kc+GTCj/dESeXBtGFqpWjaQ6SAXg0cfIKVBYE36CEiQ7h15CyIloFkt0oY4l4uTp97yD1sen2ba/452qiYr86CN+38dTJ7y+khU33YuauX6sDzX2Xs96fdwSveS5qrPC8G692gOKz8o0IiYQdQJEGdmuk/yj4r2JmODQHDhbQG7QFbEKvcveBKw/6sMci1M7JgmFiOKb6nyy+fOXSaC9/wYREH8G0rZ+fzCPkmQ4y3/2o48u/93mhHDw9weTnY/Zj1n1H22SIXsUKMz+mLnT5L9VOgkACIqCfGQLT3MYaJIEenvmOB5QKXwnxR2BeRSo18PkNArJKZo6F7gfe9E9OfUj6z/O6331oYA+ufUmOQ6pglv/svYCPvE60T48YkeKm1gCm8X8jgv37Rn8h9FqD3Wj8EBfOEdZy8n4M8fo2U3GxlITbeLG/0nFW85FSNVOB4Ohbv0dFR4LH30Aa2QqYrhji2AtsZp08jzMvM6SFJ0/mcwqrBe/Xa6tjDplUp7Jd7gpo="
